mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
]

polls/urls.py
from django.urls import path
from . import views

app_name='polls'

urlpatterns = [
                path('', views.index, name='index'),
                path('<int:question_id>/',views.detail,name='detail'),
                path('<int:question_id>/result',views.result, name='result'),
                path('<int:question_id>/vote',views.vote, name='vote'),

]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Question

def index(request):
    #return HttpResponse("Hello, world. You're at the polls index.")
    latest_question_list=Question.objects.order_by('pub_date')[:5]
    """output=','.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)"""
    context={'latest_question_list':latest_question_list}
    return render(request, 'polls/index.html', context)
def detail(request,question_id):
    #return HttpResponse("you are looking at the question %s"%question_id)
    question=get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question':question})

def result(request,question_id):
    respomse="you are looking ar the results of question %s."
    return HttpResponse(respomse %question_id)

def vote(request,question_id):
    return HttpResponse("You are voting on %s" %question_id)

polls/templates/polls/detail.html
<!DOCTYPE html>
<head><title style="color: brown;">Detail Page</title></head>
<body style="color: burlywood;">
    <h1 style="text-align: center ;background-color: black; color: blanchedalmond;">DETAIL Page</h1>
    <br>
    <h1>{{question.question_text}}</h1><ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<head><title style="color: brown;">Home Page</title></head>
<body style="color: burlywood;">
    <h1 style="text-align: center ;background-color: black; color: blanchedalmond;">INDEX PAGE</h1>
    <br>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <!--<li><a href="/polls/{{question.id}}">{{question.question_text}}</a></li>-->
            <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>

        {% endfor %}
    </ul>
    {% else %}
        <p style="background-color: cadetblue;color: crimson;">No polls are available</p>
    {% endif %}    
</body>
</html>